import { expect, test, type Page } from "@playwright/test"

async function openHome(page: Page) {
  await page.goto("/design-demo")
  await expect(page.getByRole("button", { name: "选择研究模式" })).toBeEnabled()
}

test("desktop composer stays centered and supports keyboard, examples and login return", async ({ page }) => {
  for (const viewport of [{ width: 1440, height: 900 }, { width: 1366, height: 768 }]) {
    await page.setViewportSize(viewport)
    await openHome(page)
    const box = await page.getByRole("region", { name: "研究提问框" }).boundingBox()
    expect(box).not.toBeNull()
    expect(Math.abs(box!.x + box!.width / 2 - viewport.width / 2)).toBeLessThan(2)
    expect(Math.abs(box!.y + box!.height / 2 - viewport.height / 2)).toBeLessThan(2)
    const cards = page.locator("#modules > a")
    await expect(cards).toHaveCount(4)
    const positions = await cards.evaluateAll(items => items.map(item => item.getBoundingClientRect().toJSON()))
    expect(positions[0].y).toBe(positions[1].y)
    expect(positions[2].y).toBe(positions[3].y)
    expect(positions[2].y).toBeGreaterThan(positions[0].y)
  }
  await page.getByRole("button", { name: "选择研究模式" }).click()
  await expect(page.getByRole("menu")).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("menu")).not.toBeVisible()
  await page.getByRole("button", { name: "选择研究模式" }).click()
  await expect(page.getByRole("menu")).toBeVisible()
  await page.getByRole("heading", { name: "Ask. Discover." }).click()
  await expect(page.getByRole("menu")).not.toBeVisible()
  await page.getByRole("button", { name: "选择研究模式" }).focus()
  await page.keyboard.press("ArrowDown")
  await expect(page.getByRole("menu")).toBeVisible()
  await expect(page.getByRole("menuitem").filter({ hasText: "根据问题选择合适的模块" })).toBeFocused()
  await page.keyboard.press("ArrowDown")
  await expect(page.getByRole("menuitem").filter({ hasText: "找论文" })).toBeFocused()
  await page.keyboard.press("ArrowDown")
  await expect(page.getByRole("menuitem").filter({ hasText: "找项目" })).toBeFocused()
  await page.keyboard.press("Enter")
  await expect(page.getByRole("button", { name: "选择研究模式" })).toHaveText(/找项目/)
  await page.getByRole("button", { name: "找 Agent 开源框架", exact: true }).click()
  await expect(page.getByRole("textbox")).toBeFocused()
  await expect(page).toHaveURL(/\/design-demo$/)
  await page.getByRole("button", { name: "登录", exact: true }).click()
  await expect(page.getByRole("dialog")).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).not.toBeVisible()
  await expect(page.getByRole("textbox")).toHaveValue("找 Agent 开源框架")
  await page.reload()
  await expect(page.getByRole("textbox")).toHaveValue("找 Agent 开源框架")
  await page.getByRole("button", { name: "开始研究", exact: true }).click()
  await expect(page.getByRole("textbox")).toBeFocused()
})

test("report preparation saves material and notes despite an unavailable reports API", async ({ page }) => {
  await page.route("**/api/v1/search/reports?**", route => route.fulfill({ status: 503, json: { success: false, error: { message: "Reports unavailable" } } }))
  await openHome(page)
  await page.getByRole("textbox").fill("整理 Agent 研究报告")
  await page.getByRole("button", { name: "发送问题", exact: true }).click()
  await expect(page).toHaveURL(/\/reports\?.*compose=1/)
  await expect(page.getByRole("textbox", { name: "研究主题", exact: true })).toHaveValue("整理 Agent 研究报告")
  await page.getByRole("textbox", { name: "研究范围" }).fill("比较方法和可验证的证据")
  await page.getByRole("button", { name: "添加资料" }).click()
  await page.getByRole("textbox", { name: "资料 1 标题" }).fill("原始论文")
  await page.getByRole("textbox", { name: "资料 1 链接" }).fill("https://arxiv.org/abs/2401.00001")
  await page.getByRole("textbox", { name: "分析笔记" }).fill("先核对实验，再记录结论。")
  await page.getByRole("button", { name: "保存草稿", exact: true }).first().click()
  await expect(page).toHaveURL(/draft=/)
  await expect(page.getByText("报告加载失败", { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole("textbox", { name: "研究范围" })).toHaveValue("比较方法和可验证的证据")
  await expect(page.getByRole("textbox", { name: "资料 1 链接" })).toHaveValue("https://arxiv.org/abs/2401.00001")
  await expect(page.getByRole("textbox", { name: "分析笔记" })).toHaveValue("先核对实验，再记录结论。")
  await page.getByRole("link", { name: "返回首页", exact: true }).click()
  await expect(page.getByRole("button", { name: /继续上次研究/ })).toBeVisible()
  await page.getByRole("button", { name: "最近研究", exact: true }).click()
  await page.getByRole("menuitem", { name: "删除记录：整理 Agent 研究报告", exact: true }).click()
  await expect(page.getByText("继续上次研究", { exact: true })).not.toBeVisible()
})

test("ambiguous research asks once and manual project entry retains the question", async ({ page }) => {
  await openHome(page)
  await expect(page.getByRole("button", { name: "发送问题", exact: true })).toBeDisabled()
  await page.getByRole("textbox").fill("论文和开源项目")
  await page.getByRole("textbox").dispatchEvent("compositionstart")
  await page.getByRole("textbox").press("Enter")
  await expect(page.getByRole("group", { name: "确认研究方向" })).not.toBeVisible()
  await page.getByRole("textbox").dispatchEvent("compositionend")
  await page.getByRole("button", { name: "发送问题", exact: true }).click()
  await expect(page.getByRole("group", { name: "确认研究方向" })).toBeVisible()
  await page.getByRole("button", { name: "找项目", exact: true }).click()
  await expect(page).toHaveURL(/\/projects\?/)
  const destination = new URL(page.url())
  expect(destination.searchParams.get("question")).toBe("论文和开源项目")
  expect(destination.searchParams.get("entry")).toBe("home")
})
