import { expect, test } from "@playwright/test"

const slug = "sibyl-autoresearch-autonomous-research-needs-self-evolving-trial-and-error-harnesses-not-paper-g"
const readerUrl = `/design-demo/papers/${slug}/read?returnTo=${encodeURIComponent("/design-demo/papers?q=Agent&topic=cs.AI")}`

test("chapter reading reconstructs the real paper through its final appendix, figures and references", async ({ page }) => {
  test.setTimeout(90000)
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(readerUrl)
  await expect(page.getByRole("button", { name: "章节精读", exact: true })).toHaveAttribute("aria-pressed", "true")
  const body = page.getByRole("region", { name: "Open reader paper body" })
  await expect(body).toBeVisible({ timeout: 30000 })
  await expect(body.locator("iframe,canvas")).toHaveCount(0)
  const nav = page.getByRole("navigation", { name: "章节导航" })
  await nav.getByRole("button", { name: "Appendix F Governance details", exact: true }).click()
  await expect(page.locator('[id="A6"]')).toBeInViewport()
  await expect(page.locator('[id="A6"]')).toContainText("human authors must be able to understand, defend, and rewrite")
  await expect(page.locator('[id="A6.T12"] table')).toContainText("Unsafe self-modification")
  await expect(body.locator("[data-reader-section]")).toHaveCount(36)
  expect((await body.innerText()).length).toBeGreaterThan(80000)
  await nav.getByRole("button", { name: "References", exact: true }).click()
  await expect(page.locator('[id="bib"] [data-paragraph-id]')).toHaveCount(39)
  await nav.getByRole("button", { name: "1 Introduction", exact: true }).click()
  await page.locator('[id="S1"] button').filter({ hasText: /^33$/ }).first().click()
  await expect(page.locator('[id="bib.bib33"]')).toBeInViewport()
  for (const id of ["S1.F1", "S6.F2", "S6.F3", "A1.F4", "A1.F5", "A3.F6", "A4.F7"]) {
    const figure = body.locator(`[id="${id}"]`)
    await figure.scrollIntoViewIfNeeded()
    await expect.poll(() => figure.locator("img").evaluateAll(images => images.length > 0 && images.every(image => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
  }
  await expect(body.locator("img")).toHaveCount(8)
  await expect(body.locator("table")).toHaveCount(12)
  expect(await body.locator(".katex").count()).toBeGreaterThan(10)
  await page.getByRole("button", { name: "放大正文字号" }).click()
  await expect(page.getByLabel("当前正文字号")).toHaveText("20")
  await page.getByRole("button", { name: "专注", exact: true }).click()
  await expect(page.getByRole("complementary", { name: "阅读助手" })).not.toBeVisible()
  await page.getByRole("button", { name: "退出专注" }).click()
  await page.getByRole("button", { name: "阅读笔记" }).click()
  await page.getByLabel("我的阅读笔记").fill("浏览器测试笔记：核对实验设置。")
  const download = page.waitForEvent("download")
  await page.getByRole("button", { name: "导出 Markdown" }).click()
  expect((await download).suggestedFilename()).toContain("-notes.md")
  await page.reload()
  await page.getByRole("button", { name: "阅读笔记" }).click()
  await expect(page.getByLabel("我的阅读笔记")).toHaveValue("浏览器测试笔记：核对实验设置。")
  for (const width of [1366, 1440, 1920]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.getByRole("link", { name: "返回论文" }).click()
  await expect(page).toHaveURL(/q=Agent/)
  await expect(page).toHaveURL(/topic=cs.AI/)
})

test("PDF stays an optional comparison view and remembers its page without replacing chapter reading", async ({ page }) => {
  test.setTimeout(90000)
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(readerUrl)
  await page.getByRole("button", { name: "PDF 对照", exact: true }).click()
  const pageInput = page.getByRole("spinbutton", { name: "页码", exact: true })
  await expect(pageInput).toBeEnabled({ timeout: 30000 })
  const totalPages = Number(await pageInput.getAttribute("max"))
  expect(totalPages).toBeGreaterThan(1)
  await pageInput.fill(String(totalPages))
  await pageInput.press("Enter")
  await expect(page.locator(`[aria-label$="PDF 第 ${totalPages} 页可选择文本"]`)).not.toBeEmpty({ timeout: 20000 })
  await expect(page.getByRole("button", { name: "下一页", exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole("button", { name: "章节精读", exact: true })).toHaveAttribute("aria-pressed", "true")
  await expect(pageInput).toHaveCount(0)
  await page.getByRole("button", { name: "PDF 对照", exact: true }).click()
  await expect(pageInput).toHaveValue(String(totalPages), { timeout: 30000 })
})
